---
title: "GradeAnalysis"
author: "Max"
message: false
format: 
  html:
    echo: false
---

```{r message=FALSE}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(vroom)
library(stringr)
```
## Question 1
```{r message=FALSE}
grades<-vroom(here("grades.csv"))
```

## Question 2
```{r}
grades|>
  summarise(MinGrade=min(`Exam`,na.rm=TRUE),MaxGrade=max(`Exam`,na.rm=TRUE),MedianGrade=median(`Exam`,na.rm=TRUE),AvgGrade=mean(`Exam`,na.rm=TRUE))|>
  knitr::kable()
```


## Question 3
```{r}
nb_stud_exam<-sum(is.na(grades$Exam))
```
There is a total of `r nb_stud_exam` students who did not passed the test

## Question 4
```{r}
ggplot(grades, aes(x=Exam))+
  geom_histogram(binwidth=2.5,fill="darkblue",color="black",alpha=0.7,na.rm=TRUE)+
  labs(title= "Distribution of Exam grades",
       x="Exam grades",
       y= "Frequency")
```
## Question 5
```{r}
nb_grp_split<- grades|>
  group_by(Group)|>
  summarise(N=n())
nb_grp_split|>knitr::kable()
```

## Question 6
```{r}
ggplot(nb_grp_split,aes(x=Group,y=N))+
  geom_col(fill="darkred", alpha=0.7)+
  labs(title="Number of students per group",x="Group",y="Number of students")
```


## Question 7 
```{r}
ggplot(grades,aes(y=Exam, fill=Group))+
  geom_boxplot()+
  labs(title="Distribution of exams grades by group", x="Group",y="Exam grades")+coord_flip()

ggplot(grades, aes(x=Exam, fill=Group))+
  geom_density(alpha=0.7)+
  labs(title="Distribution of exams grades by group", x="Exam grades",y="Density")+facet_wrap(~Group, ncol=4)
```


## Question 8
```{r}
missed_exam<- grades|>group_by(Group)|>summarise(Nb_Missed_Exam=sum(is.na(Exam)))
knitr::kable(missed_exam)
```
## Question 9
```{r}
ggplot(missed_exam,aes(x=Group,y=Nb_Missed_Exam))+
  geom_col(fill="blue")+
  labs(title="Missing students to the final exam by group", x="Groups",y="Number of missing students")+
  coord_flip()
```

## Question 10
```{r}
longgrade<-pivot_longer(grades,cols=c(Exam,starts_with("MCQ"),starts_with("Online")),names_to="name",values_to="value")
knitr::kable(longgrade)
```
## Question 11
```{r}
missing_grades<-longgrade|>group_by(Id)|>summarise(total_missing=sum(is.na(value)))
knitr::kable(missing_grades)
```
## Question 12
```{r}
ggplot(data = missing_grades, aes(x = Id, y = total_missing)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(
    title = "Distribution of Missing Grades per Student",
    x = "Student ID",
    y = "Number of Missing Grades"
  ) 
```
## Question 13
```{r}
missing_stud_per_grp<-longgrade|>group_by(Group)|>filter(name=="Exam")|>summarise(num_missing=sum(is.na(value)))
knitr::kable(missing_stud_per_grp)
```
## Question 14
```{r}
online_mcq_data<-longgrade|>filter(str_starts(name,"Online"))
missing_onlgrade_per_stud<-online_mcq_data|>group_by(Id)|>summarise(num_missing=sum(is.na(value)))
knitr::kable(missing_onlgrade_per_stud)
```
## Question 15

```{r}
result<-grades|>rowwise()|>mutate(missingonlinegrades=sum(is.na(c_across(starts_with("Online")))))

ggplot(result,aes(x=Exam))+
  geom_histogram(binwidth=1,fill="blue",color="black")+
  facet_wrap(~missingonlinegrades)
```
## Question 16
```{r}
missed_mcq <- longgrade |>
  group_by(Id) |>
  summarise(Missed = any(is.na(value) & str_starts(name, "MCQ_"))) 
knitr::kable(missed_mcq)
```

## Question 17
```{r}
group_missed_percentage <- missed_mcq |>
  inner_join(grades |> select(Id, Group), by = "Id") |>
  group_by(Group) |>
  summarise(P_missed = mean(Missed) * 100)

knitr::kable(group_missed_percentage)

```
## Question 18
```{r}
average_exam_grade <- grades |>
  group_by(Group) |>
  summarise(Average_Exam_Grade = mean(Exam, na.rm = TRUE))

merged_data <- inner_join(average_exam_grade, group_missed_percentage, by = "Group")

ggplot(merged_data, aes(x = P_missed, y = Average_Exam_Grade)) +
  geom_point() +
  labs(
    title = "Average exam grade vs percentage of missed MCQ",
    x = "Percentage of missed MCQ",
    y = "Average exam grade"
  )
```
